version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Docker-file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Docker-file
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
